# Generated by Django 4.1.3 on 2022-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating_author',
            field=models.IntegerField(default=0),
        ),
    ]
