# Generated by Django 4.1.3 on 2022-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_rating_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_rel',
            field=models.ManyToManyField(related_name='news', through='news.PostCategory', to='news.category'),
        ),
    ]
