# Generated by Django 4.1.3 on 2022-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_category_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_rel',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
    ]
